export enum ErrorCode {
    // Validation
    NO_FIELDS_TO_UPDATE = "NO_FIELDS_TO_UPDATE",
    CURRENT_PASSWORD_REQUIRED = "CURRENT_PASSWORD_REQUIRED",
    INVALID_EMAIL = "INVALID_EMAIL",
    MISSING_USER_DATA = "MISSING_USER_DATA",

    // Authentication & Authorization
    USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD",
    NOT_A_MEMBER = "NOT_A_MEMBER",
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
    FORBIDDEN_ACTION = "FORBIDDEN_ACTION",

    // User
    USER_NOT_FOUND = "USER_NOT_FOUND",
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",

    // Company
    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND",
    OWNER_NOT_FOUND = "OWNER_NOT_FOUND",
    NO_ACTIVE_COMPANY = "NO_ACTIVE_COMPANY",
    NO_MEMBERSHIP_FOUND = "NO_MEMBERSHIP_FOUND",
    CANNOT_JOIN_OWN_COMPANY = "CANNOT_JOIN_OWN_COMPANY",
    JOIN_REQUEST_NOT_ALLOWED = "JOIN_REQUEST_NOT_ALLOWED",
    JOIN_REQUEST_ALREADY_EXISTS = "JOIN_REQUEST_ALREADY_EXISTS",
    JOIN_REQUEST_NOT_FOUND = "JOIN_REQUEST_NOT_FOUND",

    // Invitations
    INVITE_NOT_FOUND = "INVITE_NOT_FOUND",
    INVITE_ALREADY_USED = "INVITE_ALREADY_USED",
    INVITE_EXPIRED = "INVITE_EXPIRED",
    INVITE_ALREADY_EXISTS = "INVITE_ALREADY_EXISTS",
    CANNOT_INVITE_SELF = "CANNOT_INVITE_SELF",
    CANNOT_INVITE_MEMBER = "CANNOT_INVITE_MEMBER",
    ONLY_OWNER_CAN_INVITE_OWNER = "ONLY_OWNER_CAN_INVITE_OWNER",
    INVITE_NOT_PENDING = "INVITE_NOT_PENDING",

    // Members
    REQUESTER_NOT_MEMBER = "REQUESTER_NOT_MEMBER",
    TARGET_NOT_MEMBER = "TARGET_NOT_MEMBER",
    CANNOT_REMOVE_OWNER = "CANNOT_REMOVE_OWNER",
    LAST_OWNER_CANNOT_BE_REMOVED = "LAST_OWNER_CANNOT_BE_REMOVED",
    CANNOT_MODIFY_OWNER = "CANNOT_MODIFY_OWNER",
    CANNOT_ASSIGN_OWNER = "CANNOT_ASSIGN_OWNER",
    OWNER_MUST_TRANSFER_BEFORE_LEAVE = "OWNER_MUST_TRANSFER_BEFORE_LEAVE",
    ONLY_OWNER_CAN_TRANSFER = "ONLY_OWNER_CAN_TRANSFER",
    NEW_OWNER_NOT_MEMBER = "NEW_OWNER_NOT_MEMBER",
    CANNOT_TRANSFER_TO_SELF = "CANNOT_TRANSFER_TO_SELF",

    // Notifications
    NO_COMPANY_MEMBERS_AVAILABLE = "NO_COMPANY_MEMBERS_AVAILABLE",
    CANNOT_SEND_TO_SELF = "CANNOT_SEND_TO_SELF",
    USER_MUST_BE_MEMBER_OR_FRIEND = "USER_MUST_BE_MEMBER_OR_FRIEND",
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
    NOT_AUTHORIZED = "NOT_AUTHORIZED",
    CANNOT_REPLY_TO_NOTIFICATION = "CANNOT_REPLY_TO_NOTIFICATION",
    FORBIDDEN_NOTIFICATION = "FORBIDDEN_NOTIFICATION",

    // Friendships
    CANNOT_ADD_YOURSELF = "CANNOT_ADD_YOURSELF",
    ALREADY_FRIENDS = "ALREADY_FRIENDS",
    FRIEND_REQUEST_ALREADY_SENT = "FRIEND_REQUEST_ALREADY_SENT",
    USER_BLOCKED = "USER_BLOCKED",
    FRIENDSHIP_NOT_FOUND = "FRIENDSHIP_NOT_FOUND",
    CANNOT_ACCEPT_OTHERS_REQUEST = "CANNOT_ACCEPT_OTHERS_REQUEST",
    FRIENDSHIP_NOT_PENDING = "FRIENDSHIP_NOT_PENDING",
    CANNOT_REJECT_OTHERS_REQUEST = "CANNOT_REJECT_OTHERS_REQUEST",

    // Account Deletion
    CANNOT_DELETE_ACCOUNT_WITH_PRIMARY_OWNER_COMPANIES = "CANNOT_DELETE_ACCOUNT_WITH_PRIMARY_OWNER_COMPANIES",
    CANNOT_DELETE_LAST_OWNER = "CANNOT_DELETE_LAST_OWNER",
}

