import { INestApplication } from "@nestjs/common";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { ErrorResponse } from "@application/dto/errors/error.response.dto";
import {
  InviteCreatedResponse,
  InviteInfoResponse,
  SuccessResponse,
} from "@application/dto/invites/invite.dto";
import {
  NotificationReadPayloadDto,
  RealtimeEventCatalogDto,
  RealtimeRoomsResponseDto,
} from "@application/dto/realtimes/realtime.dto";

export function swaggerSetup(app: INestApplication) {
  const cfg = new DocumentBuilder()
    .setTitle("Multi-Tenant API")
    .setDescription(
      [
        "## Overview",
        "SaaS multi-tenant platform with Role-Based Access Control (RBAC) supporting three roles: OWNER, ADMIN, and MEMBER.",
        "",
        "## Authentication",
        "All endpoints (except public company info) require JWT authentication via cookie (`mt_session`).",
        "Use POST /auth/signup to create an account and POST /auth/login to authenticate.",
        "",
        "## Core Modules",
        "",
        "### Auth (`/auth`)",
        "- POST /auth/signup - Create new user account",
        "- POST /auth/login - Authenticate and receive session cookie",
        "- GET /auth/profile - Get authenticated user profile",
        "- POST /auth/profile - Update user profile and notification preferences",
        "- POST /auth/accept-invites - Accept invite and create/link user to company (with signup)",
        "- GET /auth/account/primary-owner-companies - List companies where user is primary owner (creator)",
        "- GET /auth/account/member-companies - List companies where user is member (ADMIN/MEMBER)",
        "- DELETE /auth/account - Delete user account (requires deleting all primary owner companies first)",
        "- POST /auth/logout - End current session",
        "",
        "### Companies (`/company`, `/companies`)",
        "- POST /company - Create new company (user becomes OWNER)",
        "- GET /company or GET /companies - List companies user belongs to (paginated)",
        "- POST /company/:id/select - Set active company for multi-tenant context",
        "- GET /company/:id - Get company details (requires membership or public company)",
        "- GET /company/:id/public-info - Get public company info (no auth required for public companies)",
        "- PATCH /company/:id - Update company (name, logoUrl, description, is_public) - OWNER/ADMIN only",
        "- DELETE /company/:id - Delete company - OWNER only",
        "- POST /company/:id/members/:userId/leave - Leave company (notifies admins) - MEMBER/ADMIN only (userId must match authenticated user)",
        "",
        "### Memberships (`/companys/:companyId/members`)",
        "- GET /companys/:companyId/members - List all members with roles",
        "- GET /companys/:companyId/members/role - Get current user's role in company",
        "- GET /companys/:companyId/members/primary-owner - Get primary owner (creator) information",
        "- DELETE /companys/:companyId/members/:userId - Remove member - OWNER/ADMIN only",
        "- PATCH /companys/:companyId/members/:userId/role - Change member role - OWNER only",
        "- POST /companys/:companyId/members/transfer-ownership - Transfer ownership to another member - OWNER only",
        "",
        "### Invites (`/invite`, `/invites`)",
        "- POST /invite - Create company invite - OWNER/ADMIN only",
        "- GET /invites/received - List invites received by authenticated user (paginated)",
        "- GET /invites/created - List invites created by authenticated user (paginated)",
        "- GET /invites/:code - Get invite details by code",
        "- POST /invites/:code/accept - Accept invite by code",
        "- POST /invites/:code/reject - Reject invite by code",
        "- DELETE /invites/:id - Delete invite (sender) or reject received invite",
        "- DELETE /invites/batch - Delete multiple invites",
        "",
        "### Friendships (`/friendships`)",
        "- GET /friendships/search - Search users by name or email",
        "- POST /friendships/request - Send friend request",
        "- POST /friendships/accept - Accept friend request (by body)",
        "- POST /friendships/:friendshipId/accept - Accept friend request (by ID)",
        "- POST /friendships/reject - Reject friend request",
        "- DELETE /friendships/:friendshipId - Delete friendship or reject request",
        "- GET /friendships - List user's friendships (filter by status: PENDING, ACCEPTED, REJECTED)",
        "",
        "### Notifications (`/notifications`)",
        "- POST /notifications - Send notification to company members or friends",
        "  - Can target all members, specific emails, or only owners/admins",
        "  - Supports throttling for friend messages",
        "- POST /notifications/friend - Send message to a specific friend (with throttling)",
        "- GET /notifications - List user's notifications (paginated)",
        "- PATCH /notifications/:id/read - Mark notification as read",
        "- DELETE /notifications/:id - Delete single notification",
        "- DELETE /notifications/batch - Delete multiple notifications",
        "- POST /notifications/:id/reply - Reply to notification",
        "",
        "### Users (`/users`)",
        "- GET /users/search - Search users by name or email",
        "- DELETE /users/me - Delete current user account",
        "",
        "### Realtime (`/realtimes`)",
        "- GET /realtimes/rooms - Get WebSocket rooms and event catalog (handshake endpoint)",
        "- GET /realtimes/events - Get detailed event catalog with examples",
        "",
        "## WebSocket Events",
        "Connect to namespace `/rt` and subscribe to rooms:",
        "- `user:{userId}` - User-specific events",
        "- `company:{companyId}` - Company-specific events",
        "",
        "Available events:",
        "- `companys.updated` - Company metadata changed",
        "- `member.joined` - New member joined company",
        "- `member.left` - Member left or was removed",
        "- `notifications.created` - New notification created",
        "- `notifications.read` - Notification marked as read",
        "- `invites.rejected` - Invite was rejected",
        "- `invites.accepted` - Invite was accepted",
        "- `friend.request.sent` - Friend request sent",
        "- `friend.request.accepted` - Friend request accepted",
        "- `friend.request.rejected` - Friend request rejected",
        "",
        "## Error Handling",
        "All 4xx/5xx errors return JSON: `{ statusCode, code, message, timestamp, path }`",
        "- `code` field uses ErrorCode enum for type-safe error handling",
        "- Frontend translates codes to user-friendly Portuguese messages",
        "",
        "## Success Responses",
        "Success responses may include `code` field from SuccessCode enum for frontend translation.",
        "",
        "## Company Privacy",
        "- Public companies (`isPublic: true`) show info to non-members with 'Request to Join' button",
        "- Private companies show 'Access Denied' to non-members",
        "- POST /notifications with `onlyOwnersAndAdmins=true` sends join requests",
        "",
        "## Testing",
        "All endpoints are tested with 27 passing tests (24 unit + 3 integration).",
        "Test coverage includes: company flows, friendship flows, invite flows, and notification flows.",
      ].join("\n"),
    )
    .setVersion("1.5")
    .addServer("http://localhost:4000", "Local Development")
    .addCookieAuth(process.env.COOKIE_NAME || "mt_session", {
      type: "apiKey",
      in: "cookie",
      name: process.env.COOKIE_NAME || "mt_session",
    })
    .build();
  const docs = SwaggerModule.createDocument(app, cfg, {
    extraModels: [
      ErrorResponse,
      InviteCreatedResponse,
      InviteInfoResponse,
      SuccessResponse,
      NotificationReadPayloadDto,
      RealtimeRoomsResponseDto,
      RealtimeEventCatalogDto,
    ],
  });
  SwaggerModule.setup("doc", app, docs, {
    swaggerOptions: {
      persistAuthorization: true,
    },
    customSiteTitle: "Multi-Tenant API Docs",
  });
}
